# Generated by Django 6.0.3 on 2026-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience_years', models.FloatField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('open_to_work', models.BooleanField(default=False)),
                ('raw_profile_text', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='linkedin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
